# This Dockerfile creates a docker image for an already-built
# DemocracyOS app; the container WILL NOT build it for you.

# The container generated by this Dockerfile is intended to be published
# in the docker registry for being used as a source image for other containers

FROM democracyos/ubuntu-base
MAINTAINER Guido Vilariño <guido@democracyos.com>

COPY . /usr/src/democracyos/app/
WORKDIR /usr/src/democracyos/app
